# Generated by Django 3.2.5 on 2022-05-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hate_Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('ingredients', models.TextField()),
                ('ingredients_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Home',
        ),
    ]
