# Generated by Django 3.2.5 on 2022-05-20 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220520_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hate_ingredient',
            name='ingredients_id',
        ),
        migrations.RemoveField(
            model_name='hate_ingredient',
            name='user_id',
        ),
    ]
