# Generated by Django 3.2.5 on 2022-05-20 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220520_1459'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hate_Ingredient',
        ),
    ]
