# Generated by Django 3.2.5 on 2022-05-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220520_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredients',
            field=models.CharField(max_length=100),
        ),
    ]
