# Generated by Django 3.2.5 on 2022-05-20 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ingredient'),
        ('accounts', '0007_alter_ingredient_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hate_ingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ingredient'),
        ),
    ]
