# -*- coding: utf-8 -*-
"""유제품 전처리.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12-JMbbHqjbVUaGspIqclR12KiP3ZGHrE
"""

import pandas as pd
import pickle

with open ('/content/drive/MyDrive/Data/food_list.p', 'rb') as f:
  food = pickle.load(f)

df= pd.read_csv('/content/재료.csv')
df.to_excel('재료.xlsx')

dairyproducts = {'유제품': ['파마산', '플레인', '플레인요구르트', '프로볼로네', '카망베르', '휘핑크림',
                  '크림치즈', '사워크림', '피자치즈', '코코넛 밀크', '우유', '하바티', '요커트', '분유',
                  '탈지분유', '문스터', '스트링치즈', '파마산치즈가루', '플레인요거트', '파마산치즈', '리코타',
                  '생크림', '버터', '생모차렐라', '에담', '모차렐라치즈', '치즈', '훈제치즈', '파르메산', '페타',
                  '에멘탈', '요구르트', '치즈가루', '키리', '브리', '크림', '슬라이스치즈', '체다치즈', '코코넛 크림',
                  '그뤼에르', '슬라이스체더', '마스카포네 치즈', '모짜렐라치즈', '체다슬라이스치즈', '연유', '코티지',
                  '모짜렐라','아이스키림']}

