# Generated by Django 4.0.4 on 2022-05-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingredients', models.TextField()),
                ('ingredients_pre', models.TextField()),
                ('url', models.URLField()),
                ('serving', models.IntegerField()),
                ('cnt', models.IntegerField()),
                ('cluster', models.IntegerField()),
                ('image_url', models.URLField()),
                ('tag', models.TextField()),
                ('category', models.TextField()),
                ('bak', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.TextField()),
            ],
        ),
    ]
