# Generated by Django 3.2.5 on 2022-05-22 03:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20220522_1217'),
        ('home', '0002_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='hate_users',
            field=models.ManyToManyField(related_name='hate_ingredients', through='accounts.Hate_Ingredient', to=settings.AUTH_USER_MODEL),
        ),
    ]
