# Generated by Django 4.0.4 on 2022-06-09 01:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0002_ingredient_hate_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='like_users',
            field=models.ManyToManyField(related_name='like_recipes', through='accounts.Like_recipe', to=settings.AUTH_USER_MODEL),
        ),
    ]
